
% MATLAB Code from Sensor Array Analyzer App

% Generated by MATLAB 24.1 and Phased Array System Toolbox 24.1

% Generated on 02-Apr-2025 10:00:15

% Create a Uniform Linear Array Object
Array = phased.ULA('NumElements',2,...
    'ArrayAxis','y');
% The multiplication factor for lambda units to meter conversion
Array.ElementSpacing = 0.5*1;
Array.Taper = ones(1,2).';

% Create an gaussian antenna element
Elem = phased.GaussianAntennaElement;
Elem.FrequencyRange = [0 300000000];
Elem.Beamwidth = [10 10];
Array.Element = Elem;

% Assign Frequencies and Propagation Speed
Frequency = 300000000;
PropagationSpeed = 300000000;

N = 20;
incr = 360/N;
SteeringAngles = [
    [-180 + [0:N]*incr];
    zeros(1, N + 1)
    ]; 
% Assign Phase shift quantization bits
PhaseShiftBits = 0;


% Find the weights
w = zeros(getNumElements(Array), length(Frequency));
for idx = 1:length(SteeringAngles)
    SteerVector = phased.SteeringVector('SensorArray', Array,...
        'PropagationSpeed', PropagationSpeed, ...
        'NumPhaseShifterBits', PhaseShiftBits(1));
    w(:, idx) = step(SteerVector, Frequency(1), SteeringAngles(:, idx));
end





% Plot 2d azimuth graph
format = 'polar';
cutAngle = 0;
plotType = 'Directivity';
plotStyle = 'Overlay';
figure;
% Animation 
pause(2)
for i = 1: length(w)
    pattern(Array, Frequency, -180:180, cutAngle, 'PropagationSpeed', PropagationSpeed,...
        'CoordinateSystem', format ,'weights', w(:, i), ...
        'Type', plotType, 'PlotStyle', plotStyle);
    legend("phaseshift = " + string(SteeringAngles(1, i)))
    pause(0.5)
end 